FROM python:3.12.5

WORKDIR /app

ADD . /app

RUN pip install -r requirements.txt  --root-user-action=ignore

ENV FLASK_APP app.py
ENV FLASK_DEBUG 1

EXPOSE 8880

CMD ["flask", "run", "--host=0.0.0.0", "--port=8880"]
