FROM python:3.12.5

WORKDIR /app

ADD . /app

RUN pip install -r requirements.txt --root-user-action=ignore

EXPOSE 8888

CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
